run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true